### ISSUE TITLE
Adjustable Control Rods

### ISSUE THREAD

**Issue by Kimax89** [ThorsCrafter/Reactor-and-Turbine-control-program#17]
Before i begin, i would like to say thank you for taking the time to write these awesome scripts. Cant wait to see where this is going.

So. One thing i noticed right away, was the missing element of controlling the Control Rods in manual mode.

Would be a nice thing to have for us who goes after efficiency.

**Comment by ThorsCrafter** [comment]
First, thanks for your feedback. I will work on the reactor only mode in the next update anyway, so adding this won't be a problem. Stay tuned for it. If you want to test this (and help me developing of course) try using the beta version.

**Comment by Kimax89** [comment]
I'm allready running the Beta and havent had a single problem so far.

**Comment by ThorsCrafter** [comment]
Thats good to hear :)

**Comment by ThorsCrafter** [comment]
I will change the Reactor-only mode anyway in 2.6, so adding this won't be much of a problem ;)

**Comment by ThorsCrafter** [comment]
Added in reactor mode. commit bbf75e6acc0e28456235d57231715f12ebfafabf

**Comment by Kimax89** [comment]
i will give it a look. Still building my test-lab where i can test all the different scenarios.

**Comment by ThorsCrafter** [comment]
Great. Please give me some feedback how it works. :)

**Comment by Kimax89** [comment]
If you wanna join my server and test all this together with me.

Then here is all the info for my server [http://wattup.eu/index.php/projects/minecraft](http://wattup.eu/index.php/projects/minecraft)

**Comment by ThorsCrafter** [comment]
Ok. I'll have a look :)

**Comment by ThorsCrafter** [comment]
This seems fine. I will close that one.
