### ISSUE TITLE
Efficiency Measurement

### ISSUE THREAD

**Issue by Kimax89** [ThorsCrafter/Reactor-and-Turbine-control-program#18]
Another small thing that could be useful is to show how much RF you get per mB.
The equation is really simple. It's just the RF-production divided with the Fuel Consumption.
RF/mB is the key factor when you go for maximum efficiency.

Another thing this could be used for is an automatic mode where it goes for maximum efficiency.
it would take some time before the computer finds the correct Rodlevel.

The optimal Core Temperatur for a passive cooled reactor is 900 C and it seems that the optimal Core Temperature for a active cooled reactor is 600 C.

**Comment by ThorsCrafter** [comment]
That's a good idea. I'll look into it.

**Comment by Kimax89** [comment]
After fooling around with turbines, i think Efficiency meter should be used with reactor-only mode.

there are many factors of getting efficiency by using turbines.

**Comment by ThorsCrafter** [comment]
I'm looking into it.

**Comment by Kimax89** [comment]
Since i'm still new to Lua, this seems like an easy thing to do.

So i will give this a go, in the next couple of days.

**Comment by ThorsCrafter** [comment]
Updated! commit 1c8038503837f83a7e973415f33bf9697fd4e78b
and commit 2033aab2fcaefa99b93d7b3cb711d676463f8c23
