### ISSUE TITLE
New menu structure

### ISSUE THREAD

**Issue by Kimax89** [ThorsCrafter/Reactor-and-Turbine-control-program#23]
It might look better if we removed some of the buttons from the program itself, and keep them in the "Main menu"

So what i suggest is that we remove "Reboot", "Options" and "Mode switch". These functions are still accessable from the "Main menu" and it will give more room on the display for more visuals and informations. + i think it looks cleaner.

**Comment by ThorsCrafter** [comment]
That's a good idea. I planned to redesign the gui anyway.

**Comment by Kimax89** [comment]
I have a few ideas for a new design, but its not too far from the one there is now.
I started on LUA scripting this week, so this is all new to me.
I know PHP already so i can easily understand the logic.

I will soon do a pull request to remove the obsolete functions from programs itself, just to begin with. Then i will try to design a new layout.
