### ISSUE TITLE
nan% Bug

### ISSUE THREAD

**Issue by ThorsCrafter** [ThorsCrafter/Reactor-and-Turbine-control-program#25]
A Bug, where the program does not shows the percentage of the Energy Storage correctly. Leads to false calculation and control.

**Comment by Kimax89** [comment]
when and how did this bug occurred?

**Comment by ThorsCrafter** [comment]
Refer to comments on my [YouTube-Channel](https://www.youtube.com/channel/UCEG-Oq2LlJwkrqYu_AvfK0Q) and [this article](http://forum.thorscrafter.de/t/bugs/22/2) in my Forum (German!)
