### ISSUE TITLE
Turbine speed reported is double actual speed

### ISSUE THREAD

**Issue by FinalDoom** [ThorsCrafter/Reactor-and-Turbine-control-program#34]
I'm not sure how to reproduce, but my setup is simple:

One reactor, one turbine, one ender IO capacitor bank, all connected along a single network cable. Network cable runs under the reactor/turbine, no extra connections. The only unusual thing is that I have extra steam going to a buildcraft tank, but it's through separate ports and unconnected to the computer.

All was well for a while (or I think it was), but I noticed after playing for a while today (could have been since startup, could have happened later on, not sure) that my turbine was slowing down and was hanging around 980 RPM. My speed in the program is set to 1820. I tried bringing the speed up manually not through the program, but as soon as I'd leave the turbine GUI, the program shut off the steam. It was then I noticed that the speed reported by the program is exactly double that reported by the turbine GUI. It's not a big deal, as my turbine makes ten times my power draw a tick, even at half speed, but it seems like a bug.

**Comment by ThorsCrafter** [comment]
Your Turbine is most likely shutting down because of your "extra" steam going out. My program calculates the required steam output very precise. It really is a problem of producing less steam then necessary (even if it is a different port). 8 recommend setting up a second reactor for your extra steam.
For the Turbine speed display bug: I'll look into it.

**Comment by FinalDoom** [comment]
Ah, quite possible. I wasn't too concerned about it shutting down. Just to update, the RPM display is correct today on logging in (single player, didn't mention that before). I'll keep an eye on it and see if I can figure out any causal relationships. Thanks for a great program :D

**Comment by ThorsCrafter** [comment]
You're welcome. I will close this issue.
