### ISSUE TITLE
[2.5] Keine RF anzeige für Turbinen

### ISSUE THREAD

**Issue by HadesDurin** [ThorsCrafter/Reactor-and-Turbine-control-program#38]
Wie der titel schon sagt:

http://prntscr.com/f7v19t

**Comment by HadesDurin** [comment]
nach einem neustart des programms geht die anzeige...
http://prntscr.com/f7v6eg

**Comment by ThorsCrafter** [comment]
Please report issues in English here on Github. If you want to report something in German, you can use my [Forum](http://forum.thorscrafter.de) for that.

_Bitte hier nur auf Englisch schreiben. Wenn dir Deutsch lieber ist, kannst du das ganz einfach in meinem [Forum](http://forum.thorscrafter.de) tun_
