### ISSUE TITLE
Monitor doesn't refresh

### ISSUE THREAD

**Issue by ghost** [ThorsCrafter/Reactor-and-Turbine-control-program#40]
Love the program!

Everything installs fine and the turbines run fine and producing enough power, however the monitor doesn't refresh and i have to click a button to get the screen to update with new values. Hope this could be resolved?

Thanks!

**Comment by ThorsCrafter** [comment]
That should be already be fixed by my newest Beta for 1.6 (which by the way will be released soon, after some more testing). You can try using my beta versions if you like.

**Comment by ghost** [comment]
That's great, thank you very much! Keep up the good work!

**Comment by ThorsCrafter** [comment]
No problem ;)
