### ISSUE TITLE
Add support for Resonant Energy Cells from Thermal Expansion.

### ISSUE THREAD

**Issue by the-glaive** [ThorsCrafter/Reactor-and-Turbine-control-program#41]
I'm on a tekkit server, and this program would be perfect, except that my only reliable storage of RF is in resonant energy cells. If you could add support for these, that would be great.

**Comment by ThorsCrafter** [comment]
In theory, the program is working with any kind of Energy Storage, which support the `getEnergyStored()` function. I tested this with Thermal Expansion Energy Cells in my Testworld in 1.7.10. What Tekkit Modpack are you playing on?

**Comment by the-glaive** [comment]
Tekkit main v1.2.10cx [1.6.4 Regular Tekkit]

Do you need me to test something?

**Comment by ThorsCrafter** [comment]
Well, there's the problem. The program is designed to work with ComputerCraft Versions 1.7 and above. Thus, Minecraft 1.7.10 is required for the program to run. It may work on lower versions in some parts, but it is not designed that way.
