### ISSUE TITLE
Mekanism Induction Matrix

### ISSUE THREAD

**Issue by rogerdeboer1993** [ThorsCrafter/Reactor-and-Turbine-control-program#45]
Hey,

I'm unable to connect the program to an Induction Matrix.
It's giving me an error saying it can't find an energy storage.

**Comment by ThorsCrafter** [comment]
It is possible, that the Induction Matrix is not compatible with the program. In which way have you connected the Matrix to the Computer? Is the Network recognize the Matrix as valid device (The modem should turn red, if enabled)?

**Comment by rogerdeboer1993** [comment]
I have tried connecting the wired modem to both the induction casing and the induction port (in input mode). Haven't tried the induction port on output mode. The network does recognize the Matrix (giving it the name "Induction Matrix_#" with a valid number for #) and modem turns red.

**Comment by ThorsCrafter** [comment]
In this case, your Matrix is indeed recognized by the computer. It probably uses a different function to get the energy value from the Matrix (something different then "getEnergyStored()"). Since I am working on Version 3.0 of the program anyway, I'll take a look at this, too. This will take some more time though. 
I recommend using a different Energy Storage in the meantime.

**Comment by rogerdeboer1993** [comment]
allright, thanks for you reply anyway. I'll try to find a solution for it as well. Looking forward to the 3.0 version.

**Comment by rogerdeboer1993** [comment]
by the way, do you know if the draconic energy core works with this program?

**Comment by ThorsCrafter** [comment]
The Draconic Core works fine. You have to put the modem on one of the Energy Pylons.

**Comment by rogerdeboer1993** [comment]
just checked another program that could read current and max power levels in an induction matrix.
code they used was:
for max power --> cube.getMaxEnergy()
for current power --> cube.getEnergy()


full program code here:
http://www.computercraft.info/forums2/index.php?/topic/19381-power-monitor-program-works-with-any-mods-power-storage/

hope this helps
